apiVersion: v1
kind: Service
metadata:
  name: fleetctl
  namespace: fleet-lab
  labels:
    app.kubernetes.io/name: fleetctl
spec:
  selector:
    app.kubernetes.io/name: fleetctl
  ports:
    - name: http
      port: 8080
      targetPort: http
